// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_define.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fdefine_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fdefine_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_5fdefine_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fdefine_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5fdefine_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace net {

enum PHP_MSG_ID : int {
  PLAT_MSG_NULL = 0,
  PLAT_MSG_PING = 10,
  PLAT_MSG_CHANGE_SAFEPWD = 11,
  PLAT_MSG_KILL_PLAYER = 12,
  PLAT_MSG_CHANGE_ACCVALUE = 13,
  PLAT_MSG_BROADCAST = 14,
  PHP_MSG_ID_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PHP_MSG_ID_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PHP_MSG_ID_IsValid(int value);
constexpr PHP_MSG_ID PHP_MSG_ID_MIN = PLAT_MSG_NULL;
constexpr PHP_MSG_ID PHP_MSG_ID_MAX = PLAT_MSG_BROADCAST;
constexpr int PHP_MSG_ID_ARRAYSIZE = PHP_MSG_ID_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PHP_MSG_ID_descriptor();
template<typename T>
inline const std::string& PHP_MSG_ID_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PHP_MSG_ID>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PHP_MSG_ID_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PHP_MSG_ID_descriptor(), enum_t_value);
}
inline bool PHP_MSG_ID_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PHP_MSG_ID* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PHP_MSG_ID>(
    PHP_MSG_ID_descriptor(), name, value);
}
enum CLIENT_MSG_ID : int {
  C2S_MSG_NULL = 0,
  C2S_MSG_HEART = 1000,
  C2S_MSG_LOGIN = 1001,
  S2C_MSG_LOGIN_REP = 1002,
  S2C_MSG_LOGINOUT_REP = 1003,
  S2C_MSG_VERSION_INFO_REP = 1004,
  S2C_MSG_ENTER_GAME = 1010,
  S2C_MSG_PLAYER_INFO = 1011,
  S2C_MSG_UPDATE_ACC_VALUE = 1012,
  C2S_MSG_REQ_SVRS_INFO = 1100,
  S2C_MSG_SVRS_INFO = 1101,
  C2S_MSG_ENTER_SVR = 1102,
  S2C_MSG_ENTER_SVR_REP = 1103,
  C2S_MSG_REPORT_GPS = 1201,
  C2S_MSG_REPORT_NET_DELAY = 1202,
  C2S_MSG_GET_GAME_RECORD = 1203,
  S2C_MSG_GET_GAME_RECORD_REP = 1204,
  S2C_MSG_SEND_ALL_MISSION_REP = 1210,
  S2C_MSG_SEND_MISSION_REP = 1211,
  C2S_MSG_GET_MISSION_PRIZE_REQ = 1212,
  S2C_MSG_GET_MISSION_PRIZE_REP = 1213,
  C2S_MSG_BACK_LOBBY = 2001,
  S2C_MSG_BACK_LOBBY_REP = 2002,
  C2S_MSG_REQ_ROOMS_INFO = 2009,
  S2C_MSG_ROOMS_INFO = 2010,
  C2S_MSG_ENTER_ROOM = 2011,
  S2C_MSG_ENTER_ROOM_REP = 2012,
  S2C_MSG_NOTIFY_LEAVE_ROOM = 2013,
  C2S_MSG_REQ_TABLE_LIST = 2014,
  S2C_MSG_TABLE_LIST = 2015,
  C2S_MSG_LEAVE_TABLE_REQ = 2020,
  S2C_MSG_LEAVE_TABLE_REP = 2021,
  C2S_MSG_ENTER_TABLE_REQ = 2024,
  S2C_MSG_ENTER_TABLE = 2025,
  S2C_MSG_TABLE_INFO = 2026,
  S2C_MSG_SEATS_INFO = 2027,
  C2S_MSG_TABLE_READY = 2028,
  S2C_MSG_TABLE_READY_REP = 2029,
  C2S_MSG_TABLE_CHAT = 2030,
  S2C_MSG_TABLE_CHAT = 2031,
  C2S_MSG_TABLE_SET_AUTO = 2032,
  S2C_MSG_TABLE_SET_AUTO = 2033,
  C2S_MSG_FAST_JOIN_ROOM = 2040,
  S2C_MSG_FAST_JOIN_ROOM_REP = 2041,
  C2S_MSG_FAST_JOIN_TABLE = 2042,
  S2C_MSG_FAST_JOIN_TABLE_REP = 2043,
  C2S_MSG_QUERY_TABLE_LIST_REQ = 2045,
  S2C_MSG_QUERY_TABLE_LIST_REP = 2046,
  S2C_MSG_NOTIFY_PLAYER_JOIN = 2047,
  S2C_MSG_LOOKER_LIST_INFO = 2048,
  C2S_MSG_SITDOWN_STANDUP = 2049,
  S2C_MSG_SITDOWN_STANDUP = 2050,
  S2C_MSG_SEAT_VALUE_INFO_REP = 2055,
  CLIENT_MSG_ID_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  CLIENT_MSG_ID_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool CLIENT_MSG_ID_IsValid(int value);
constexpr CLIENT_MSG_ID CLIENT_MSG_ID_MIN = C2S_MSG_NULL;
constexpr CLIENT_MSG_ID CLIENT_MSG_ID_MAX = S2C_MSG_SEAT_VALUE_INFO_REP;
constexpr int CLIENT_MSG_ID_ARRAYSIZE = CLIENT_MSG_ID_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CLIENT_MSG_ID_descriptor();
template<typename T>
inline const std::string& CLIENT_MSG_ID_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CLIENT_MSG_ID>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CLIENT_MSG_ID_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CLIENT_MSG_ID_descriptor(), enum_t_value);
}
inline bool CLIENT_MSG_ID_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CLIENT_MSG_ID* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CLIENT_MSG_ID>(
    CLIENT_MSG_ID_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace net

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::net::PHP_MSG_ID> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::net::PHP_MSG_ID>() {
  return ::net::PHP_MSG_ID_descriptor();
}
template <> struct is_proto_enum< ::net::CLIENT_MSG_ID> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::net::CLIENT_MSG_ID>() {
  return ::net::CLIENT_MSG_ID_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_5fdefine_2eproto
